name: Build and Deploy Darwin Arm64

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main

jobs:
  darwin-arm64:
    runs-on: ubuntu-latest
    name: Build and Deploy Darwin Arm64
    environment: production

    steps:
      - name: Checkout Hoop
        uses: actions/checkout@v3

      - name: Checkout libhoop
        uses: actions/checkout@v3
        with:
          repository: hoophq/libhoop
          path: './libhoop'
          token: ${{ secrets.GH_TOKEN }}  # Ensure token is provided here

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.4'  # Specify exact Go version
          cache-dependency-path: '**/go.sum'

      - name: Set Git Tag
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build
        env:
          GIT_TAG: ${{ env.GIT_TAG }}
        run: GOOS=darwin GOARCH=arm64 make build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifacts
          path: dist/

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ghcr.io/${{ github.repository }}/hoop:${{ env.GIT_TAG }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Push Docker Image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/hoop:${{ env.GIT_TAG }}
